name: FastApi CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    - name: Run tests with coverage
      run: |
        export PYTHONPATH=$(pwd)
        coverage run --source=app -m pytest tests/
        coverage report
      env:
        DATABASE_URL: sqlite:///:memory
        GOOGLE_API_KEY: fake-key
        MONGO_URI: mongodb://localhost:27017
        CELERY_BROKER_URL: redis://localhost:6379/0
        CELERY_RESULT_BACKEND: redis://localhost:6379/0
        SECRET_KEY: test-secret
        ALGORITHM: HS256